"""group public_id

Revision ID: 0f50a1cfc03f
Revises: b51c7f2d8648
Create Date: 2026-10-01 17:43:29.406996

"""
from typing import Sequence, Union

import secrets

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f50a1cfc03f'
down_revision: Union[str, Sequence[str], None] = 'b51c7f2d8648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('public_id', sa.String(length=16), nullable=True))

    # Существующим группам — случайный public_id, затем колонку делаем обязательной
    conn = op.get_bind()
    for (group_id,) in conn.execute(sa.text("SELECT id FROM groups")):
        conn.execute(
            sa.text("UPDATE groups SET public_id = :pid WHERE id = :id"),
            {"pid": secrets.token_urlsafe(9), "id": group_id},
        )
    op.alter_column('groups', 'public_id', nullable=False)

    op.create_unique_constraint(op.f('uq_groups_public_id'), 'groups', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_groups_public_id'), 'groups', type_='unique')
    op.drop_column('groups', 'public_id')
    # ### end Alembic commands ###
