"""initial

Revision ID: b51c7f2d8648
Revises: 
Create Date: 2026-10-01 16:31:57.634692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Зафиксировано здесь, а не импортом из app: миграция не должна меняться вместе с кодом
SYSTEM_CATEGORIES = [
    ("groceries", "🛒"), ("cafe", "🍽"), ("transport", "🚕"), ("housing", "🏠"),
    ("fun", "🎉"), ("shopping", "🛍"), ("other", "📦"),
]

# revision identifiers, used by Alembic.
revision: str = 'b51c7f2d8648'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('tg_chat_id', name=op.f('uq_groups_tg_chat_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('payment_details', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_users_tg_id'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    categories = op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_categories_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code')),
    sa.UniqueConstraint('group_id', 'name', name=op.f('uq_categories_group_id'))
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_group_members'))
    )
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_settlements_amount_positive')),
    sa.CheckConstraint('from_user_id <> to_user_id', name=op.f('ck_settlements_different_users')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_settlements_from_user_id_users')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_settlements_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_settlements_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index(op.f('ix_settlements_group_id'), 'settlements', ['group_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_expenses_category_id_categories')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expenses_created_by_users')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_expenses_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], name=op.f('fk_expenses_payer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_group_id'), 'expenses', ['group_id'], unique=False)
    op.create_table('expense_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_expense_history_expense_id_expenses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expense_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_history'))
    )
    op.create_index(op.f('ix_expense_history_expense_id'), 'expense_history', ['expense_id'], unique=False)
    op.create_table('expense_shares',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_expense_shares_amount_non_negative')),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_expense_shares_expense_id_expenses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expense_shares_user_id_users')),
    sa.PrimaryKeyConstraint('expense_id', 'user_id', name=op.f('pk_expense_shares'))
    )
    # ### end Alembic commands ###

    # Системные категории: group_id = NULL, название переводится по code
    op.bulk_insert(categories, [{"code": code, "name": code, "emoji": emoji} for code, emoji in SYSTEM_CATEGORIES])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_shares')
    op.drop_index(op.f('ix_expense_history_expense_id'), table_name='expense_history')
    op.drop_table('expense_history')
    op.drop_index(op.f('ix_expenses_group_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_settlements_group_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_table('group_members')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
