"""settlement tg_message_id

Revision ID: c549a0c7b57d
Revises: 0f50a1cfc03f
Create Date: 2026-10-01 17:44:57.782601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c549a0c7b57d'
down_revision: Union[str, Sequence[str], None] = '0f50a1cfc03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('tg_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'tg_message_id')
    # ### end Alembic commands ###
