"""group reminders

Revision ID: de1a55238c63
Revises: c549a0c7b57d
Create Date: 2026-10-01 20:57:28.740838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1a55238c63'
down_revision: Union[str, Sequence[str], None] = 'c549a0c7b57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('reminder_interval_days', sa.Integer(), server_default='7', nullable=False))
    op.add_column('groups', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'last_reminder_at')
    op.drop_column('groups', 'reminder_interval_days')
    # ### end Alembic commands ###
